# This file contains a mapping from the KeyboardEvent.code (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)
# to the key names used in the CryEngine (https://www.cryengine.com/docs/static/engines/cryengine-5/categories/23756813/pages/23306384?utm_source=chatgpt.com).

[keys]
KeyA = "a"
KeyB = "b"
KeyC = "c"
KeyD = "d"
KeyE = "e"
KeyF = "f"
KeyG = "g"
KeyH = "h"
KeyI = "i"
KeyJ = "j"
KeyK = "k"
KeyL = "l"
KeyM = "m"
KeyN = "n"
KeyO = "o"
KeyP = "p"
KeyQ = "q"
KeyR = "r"
KeyS = "s"
KeyT = "t"
KeyU = "u"
KeyV = "v"
KeyW = "w"
KeyX = "x"
KeyY = "y"
KeyZ = "z"

Digit1 = "1"
Digit2 = "2"
Digit3 = "3"
Digit4 = "4"
Digit5 = "5"
Digit6 = "6"
Digit7 = "7"
Digit8 = "8"
Digit9 = "9"
Digit0 = "0"

ArrowUp = "up"
ArrowDown = "down"
ArrowLeft = "left"
ArrowRight = "right"

F1 = "f1"
F2 = "f2"
F3 = "f3"
F4 = "f4"
F5 = "f5"
F6 = "f6"
F7 = "f7"
F8 = "f8"
F9 = "f9"
F10 = "f10"
F11 = "f11"
F12 = "f12"
F13 = "f13"
F14 = "f14"
F15 = "f15"

Numpad1 = "np_1"
Numpad2 = "np_2"
Numpad3 = "np_3"
Numpad4 = "np_4"
Numpad5 = "np_5"
Numpad6 = "np_6"
Numpad7 = "np_7"
Numpad8 = "np_8"
Numpad9 = "np_9"
Numpad0 = "np_0"
NumLock = "numlock"
NumpadDivide = "np_divide"
NumpadMultiply = "np_multiply"
NumpadSubtract = "np_subtract"
NumpadAdd = "np_add"
NumpadEnter = "np_enter"
NumpadDecimal = "np_period"

Escape = "escape"
Backquote = "tilde"
Tab = "tab"
CapsLock = "capslock"

ShiftLeft = "lshift"
ShiftRight = "rshift"
ControlLeft = "lctrl"
ControlRight = "rctrl"
AltLeft = "lalt"
AltRight = "ralt"

Space = "space"
Minus = "minus"
Equal = "equals"
Backspace = "backspace"

BracketLeft = "lbracket"
BracketRight = "rbracket"
Backslash = "backslash"
Semicolon = "semicolon"
Quote = "apostrophe"
Enter = "enter"
Comma = "comma"
Period = "period"
Slash = "slash"

Home = "home"
End = "end"
Delete = "delete"
PageUp = "pgup"
PageDown = "pgdn"
Insert = "insert"
ScrollLock = "scrolllock"
PrintScreen = "print"
Pause = "pause"
